# Generated by Django 4.2.16 on 2024-11-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloglist_date_alter_bloglist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
