# Generated by Django 4.2.16 on 2024-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/media/images'),
        ),
    ]
